//alert('com a nossa mensagem')
//window.confirm('deseja realmente apagar?')
//window.prompt('digite seu nome')
//const confirma = confirm('realmente deseja apagar?')
let numeroDigitado = prompt('digite um numero')
let numeroDigitado2 = prompt('digite outro numero')
numeroDigitado = Number(numeroDigitado)
numeroDigitado2 = Number(numeroDigitado2)
alert(`o resultado da soma dos numeros é ${numeroDigitado + numeroDigitado2}`)
